# Generated by Django 5.1.1 on 2024-09-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
